### ISSUE TITLE
Background services

### ISSUE THREAD

**Issue by shahid31346** [uzairleo/easy_geofencing#1]
Can background services be added to this package.

**Comment by uzairleo** [comment]
yes you can demonstrate that by clonning or testing the source code example

**Comment by shahid31346** [comment]
i mean when the app is killed and someone exited the geofence then i want to execute a function.

**Comment by uzairleo** [comment]
you can brother there are callbacks for that or if you unfortunately cant get your work form builtin callbacks than go for platform channels

**Comment by uzairleo** [comment]
i got your point now you are asking for outside app geofencing when the app is even closed yes u r right the plugin is just for in app geofencing or when the app is in background thanks for figuring out this issue i will sooner add that background feature and then merge the updated code

**Comment by shahid31346** [comment]
Thank you very much for replying, Yes please i am in need of it, i am stuck in a project on this point.

**Comment by shahid31346** [comment]
I want to send notification when someone exiting geofence.

**Comment by shahid31346** [comment]
hi any update on the request?

**Comment by deepakrana0011** [comment]
@shahid31346 have you get any solution for this?
