### ISSUE TITLE
Add google maps

### ISSUE THREAD

**Issue by Sarat-1997** [uzairleo/easy_geofencing#10]
How to add google maps with the help of geofence?

**Comment by MustafaRazaUllah** [comment]
geofence is separate thing and Google map is separate thing. google map provide you map location with (Lat, Log, Place ID and Place Name.. etc) but geofence is only provide specific area radius when user Enter and Out form there place then they Event trigger on your action.

**Comment by uzairleo** [comment]
Hi @Sarat-1997 for that you have to utlize this package and use google maps separately since as @MustafaRazaUllah mentioned Google map is a different functionality and map is a different and not yet supported in the latest version of package
