### ISSUE TITLE
Have you got an updated example for flutter 2.5?

### ISSUE THREAD

**Issue by sarahk** [uzairleo/easy_geofencing#2]
I'm messing about and will post if I get it working but the examples don't work straight away.

**Comment by uzairleo** [comment]
Its under development i have migrate the entire package and its example to null safety let me do some testing then i will push the code

**Comment by uzairleo** [comment]
@sarahk  hi there i have fixed the issue and updated the dependency thanks for reporting its working now with sound null safety :)
