### ISSUE TITLE
How to listen to more than one geofence?

### ISSUE THREAD

**Issue by aeg6430** [uzairleo/easy_geofencing#8]
I tried to edit  the  `StreamController<GeofenceStatus>` to `StreamController<GeofenceStatus.broadcast()>` but it didn't worked

**Comment by HudaLatheef** [comment]
@aeg6430 add geofenceStatusStream = null in geofence stop service as below:

setState(() {
              geofenceStatus = status.toString();
              EasyGeofencing.stopGeofenceService();
              geofenceStatusStream!.cancel();
              geofenceStatusStream = null;
            });

**Comment by Soliardi-Chyngyz** [comment]
Same issue, author has idea?  @HudaLatheef  I did same but get other  - **Bad state: Stream has already been listened to**

**Comment by Soliardi-Chyngyz** [comment]
It seems I found a solution

Inside the library (class EasyGeofencing() ) add .broadcast() to the controller

Total
static StreamController<GeofenceStatus> _controller =
       StreamController<GeofenceStatus>.broadcast();

and in the method where you call stop, do this:
EasyGeofencing.stopGeofenceService();
geofenceStatusStream?.cancel();
geofenceStatusStream = null;

at least my friends work

**Comment by uzairleo** [comment]
Fixed and available in latest version .
