### ISSUE TITLE
Background (Even when app is killed)

### ISSUE THREAD

**Issue by Tristannos** [uzairleo/easy_geofencing#9]
Could you implement that the callbacks work even when the app is killed?

Just like the question #1

**Comment by uzairleo** [comment]
yes indeed i will sooner i will update this

**Comment by Neillbar** [comment]
Hi, any update on this, has this been implemented ?

**Comment by youssefasultan** [comment]
is it implemented yet?

**Comment by hpsolver** [comment]
Hi @uzairleo is implemented ?

**Comment by saurabhkumar8112** [comment]
To support this feature you can run a background process and pass the logic of geofencing to it.
https://pub.dev/packages/flutter_background_service

**Comment by uzairleo** [comment]
Thanks @saurabhkumar8112 for providing the workaround yeap thats right you guys can use that flutter background service and pass the geofencing logic apart from that i am unable to maintain this repo these days .

**Comment by kyadalu1** [comment]
try this https://www.youtube.com/watch?v=Z_wBnBjHb6U

**Comment by Tristannos** [comment]
> try this https://www.youtube.com/watch?v=Z_wBnBjHb6U

The video is scheduled 90 days from now.....
